# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='zanr',
        ),
    ]
