# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0002_auto_20171001_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='film_title',
            new_name='naziv_filma',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='film_logo',
            new_name='plakat',
        ),
    ]
