# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0003_auto_20171001_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='naziv_pesme',
        ),
    ]
