# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0004_auto_20171001_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='zanr',
        ),
        migrations.AddField(
            model_name='film',
            name='godina',
            field=models.CharField(default=1900, max_length=4),
            preserve_default=False,
        ),
    ]
